language: node_js
node_js:
  - "stable"
services:
  - postgresql
env:
  - NODE_ENV=development
before_script:
  - npm run build && psql -c 'create database kinectdb;' -U postgres && redis-server /usr/local/etc/redis.conf --port 6380